<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>YARG_remote</AssemblyName>
    <Product>YARG Remote</Product>
    <Version>1.1.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <!-- CAMINHO DO JOGO: Centralizado aqui para facilitar alterações futuras -->
    <GameDir>$(LOCALAPPDATA)\YARC\YARG Installs\a7a5552a-a374-4cda-a648-22af1d24ec09\installation</GameDir>
    <ManagedDir>$(GameDir)\YARG_Data\Managed</ManagedDir>
    <BepInExDir>$(GameDir)\BepInEx\core</BepInExDir>
  </PropertyGroup>

  <ItemGroup>
    <!-- BepInEx -->
    <Reference Include="BepInEx">
      <HintPath>$(BepInExDir)\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExDir)\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- Unity -->
    <Reference Include="UnityEngine">
      <HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(ManagedDir)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(ManagedDir)\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>$(ManagedDir)\Unity.Addressables.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.ResourceManager">
      <HintPath>$(ManagedDir)\Unity.ResourceManager.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- YARG -->
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>$(ManagedDir)\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- YARG -->
    <Reference Include="YARG.Core">
      <HintPath>$(ManagedDir)\YARG.Core.Package.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
