<!-- <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    
    <Reference Include="UnityEngine">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="YARG.Core">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\YARG.Core.dll</HintPath>
      <Aliases>YargCore</Aliases>
    </Reference>

    <Reference Include="Unity.TextMeshPro">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    
  </ItemGroup>

</Project> -->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>MSB3277</NoWarn>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="YARG.Core">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\YARG.Core.Package.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>C:\Users\GuguTab\AppData\Local\YARC\YARG Installs\0eb8f386-1d56-406c-8367-76a5f84426a5\installation\YARG_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
